---
title: "Report template"

Note:

Originally, I was planning to replicate both study 1 & 2, out of series of 5 studies in the original paper. However, in a candid moment of self-evaluation, I realized that given my competency in js and the number of participants I can hire, it might be more pragmatic idea to only focus on the study 1. I appreciate any feedback in this regard.

















-- REPORT TEMPLATE --
				
					
Replication of Study A Gender Bias in the Attribution of Creativity: Archival and Experimental Evidence for the Perceived Association Between Masculinity and Creative Thinking 		
         by 		
					
Devon Proudfoot, Aaron C. Kay, and Christy Z. Koval 
				
			
		
 (2015, Psychological Science)

Shima Salehi
salehi@stanford.edu


#Introduction

The goal of this study was to examine whether in terms of creativity men and their works would be evaluated differently than women and their works. In other words, whether the judgement of creativity is influenced by the gender of a creator. To test this hypothesis, the authors asked participants to rate creativity of stereotypically masculine characteristics as well as stereotypically feminine characteristics. The researchers compared whether the attribution of creativity varied significantly across gendered characteristics. Furthermore, authors were interested to speculate that given there might be a gender bias for attribution of creativity, this bias could be moderated by how creativity is defined. They used two different definitions for creativity: 1. divergent thinking: thinking outside the box, 2. convergent thinking: bringing pieces together and connecting the dots. They decided on these two definitions, because these definition are aligned with agency and communality divide, which has been associated with masculinity and femininity divide. Therefore, authors pursued whether by defining creativity as a communal and more feminine traits versus. a more agent and masculine trait, they can manipulate the potential gender bias in attribution of creativity.

#Methods

Power Analysis
	Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

#Planned Sample
 Planned sample size will be decided after power analysis. Same as the original study, we will limit the participants to Americans older than 18 year old. The rule of termination will depend on power analysis and consequential planned sample size. The original author in advance decide to terminate the data collection as they reach the planned sample size.

#Materials & Procedure
	Study1:

“Participants were randomly assigned to one of two conditions. Participants in the divergent-thinking condition read a passage describing creativity as the ability to “think outside the box,” see the world differently than the average person does, and create things that do not conform to traditions. Participants in the convergent-thinking condition read that creativity is the ability to “connect the dots,” see the connections between disparate ideas, and create things that bring ideas together in a unique way (see the Supplemental Material for the text used for this manipulation).
						
Participants then rated, on a 9-point scale, how central 16 personality traits were to creativity, as described in the passage. Eight of the traits were stereotypically masculine-agentic (decisive, competitive, self-reliant, willing to take risks, ambitious, daring, adventurous, courageous), and 8 were stereotypically feminine-communal (sensi- tive, cooperative, understanding of others, helpful to others, sympathetic, nurturing, warm in relations with others, and supportive; cf. Prentice & Carranza, 2002). An exploratory factor analysis with varimax rotation revealed a two-factor structure. The 8 masculine-agentic traits loaded onto one factor, so ratings of these traits were combined (α = .88). The 8 feminine-communal traits loaded onto the other factor, so ratings of these traits were combined (α = .92).”

#Study 2:
					
“Participants were randomly assigned to one of four experimental conditions in which they read background information about either an architect (male or female) or a fashion designer (male or female). All information was identical across conditions except for the target’s profession and gender (which was manipulated by varying the first name; see the Supplemental Material for the text used for the manipulation). Participants were then instructed to examine the target’s work, which was identical in the two gender conditions. In the architecture condition, participants saw three images of houses. Two of the images were of Villa Freundorf (designed by Project A01 Architects), and one of the images was of Home Spa (designed by architekti.sk). In the fashion-design condition, participants saw three images of fashion designs from the 2013 Pratt Fashion Show (designs were by Sam O’Brien, Jefferson Musanda, and Raya Kassisieh, respectively). After viewing one of these sets of images, participants assessed the target’s creativity, originality, and outside-the-box thinking; these ratings were combined to form a composite score for creativity (α = .84). Participants also assessed how talented and gifted the target was; these ratings were combined to form a composite score for competence (r = .92, p < .001; see the Supplemental Material for the six creativity and competence items).”


#Analysis Plan

Study1:
Same as the authors of original paper, we are going to conduct “a mixed-model ANOVA with condition as the between-subjects factor and trait type as the within-subjects factor”. After that we will conduct a series of follow up tests to confirm the main effects as well as interaction. For both conditions separately, we will compare the average creativity score across gendered characteristics. Furthermore, for each group of gendered characteristics, we will compare the average creativity score across conditions.

Study 2:
	Same as the authors of original paper, we will “ conduct a 2 (target’s gender: male vs. female) × 2 (domain: architecture vs. fashion design) between- subjects ANOVA with creativity ratings as the dependent measure to examine whether the male target was judged as more creative than the female target, and whether domain moderated this effect.” To further examine we will conduct another ANOVA test controlling for perceived competency of a designer.	

Differences from Original Study
There is no planned difference from the original study, except that there would be a smaller number of participants.

#Actual Sample
	Study 1:	 	 	 		
In the original study, eighty participants (49% female, U.S. residents) were recruited from Amazon Mechanical Turk (see Table S1 in the Supplemental Material for additional demographic information). Demographic variables did not moderate the results. 
  Study 2:									
In the original study, one hundred sixty-nine participants (36% female, U.S. residents) were recruited from Amazon Mechanical Turk, in accord with our goal of recruiting 40 participants per experimental group 


Differences from pre-data collection methods plan
	None.


#Results

Data preparation
	Data preparation following the analysis plan.

Confirmatory analysis
	The analyses as specified in the analysis plan

Exploratory analyses
Any follow-up analyses desired (not required).

#Discussion

Summary of Replication Attempt
Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

Commentary
Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.

